name: Test Model
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependancies
        run: pip install -r requirements.txt
      - name: Run basic test
        run: python -c "import tensorflow as tf; print(tf.__version__)"
